-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 16:43:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema sismedic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sismedic` ;

-- -----------------------------------------------------
-- Schema sismedic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sismedic` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ciudades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ciudades` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `IdProvincia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Fk_IdProvincia` ON `ciudades` (`IdProvincia` ASC) INVISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permisos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `permisos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Insertar` INT NOT NULL,
  `Editar` INT NOT NULL,
  `Consultar` INT NOT NULL,
  `Eliminar` INT NOT NULL,
  `IdRol` INT NOT NULL,
  `Modulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Fk_IdRolPermiso` ON `permisos` (`IdRol` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provincias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `provincias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Codigo` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Estado` INT NULL,
  `deleted_at` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `sismedic` ;

-- -----------------------------------------------------
-- Table `citageneral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citageneral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `citageneral` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `MotivoConsulta` VARCHAR(255) NULL DEFAULT NULL,
  `Anamnesis` VARCHAR(255) NULL DEFAULT NULL,
  `ExamenFisico` VARCHAR(200) NULL DEFAULT NULL,
  `Talla` DOUBLE NULL DEFAULT NULL,
  `Peso` DOUBLE NULL DEFAULT NULL,
  `PresionArterial` DOUBLE NULL DEFAULT NULL,
  `Pulso` DOUBLE NULL DEFAULT NULL,
  `MasaCorporal` VARCHAR(10) NULL DEFAULT NULL,
  `PerímetroCefálico` DOUBLE NULL DEFAULT NULL,
  `Diagnostico` VARCHAR(255) NOT NULL,
  `Tratamiento` VARCHAR(255) NOT NULL,
  `Estado` VARCHAR(15) NULL,
  `FechaSistema` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `IdEmpresa` INT(11) NOT NULL,
  `IdProfesional` INT(11) NOT NULL,
  `IdPaciente` INT(11) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `citaodontologicadetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citaodontologicadetalle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `citaodontologicadetalle` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdCitaOdontologica` INT(11) NOT NULL,
  `IdPiezadental` INT(11) NOT NULL,
  `Tratamiento` VARCHAR(255) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `citaodontologicamaestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citaodontologicamaestro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `citaodontologicamaestro` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `FechaCita` DATE NOT NULL,
  `MotivoCita` VARCHAR(45) NULL,
  `FechaSistema` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Estado` VARCHAR(15) NOT NULL DEFAULT 'Pendiente',
  `IdPaciente` INT(11) NOT NULL,
  `IdProfesional` INT(11) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empresa` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Identificacion` VARCHAR(13) NOT NULL,
  `RazonsSocial` VARCHAR(200) NOT NULL,
  `NombreComercial` VARCHAR(200) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Correo` VARCHAR(70) NOT NULL,
  `Telefono` VARCHAR(25) NOT NULL,
  `Celular` VARCHAR(25) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `imagencita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imagencita` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `imagencita` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdCitaGeneral` INT(11) NULL DEFAULT NULL,
  `IdCitaOdontologia` INT(11) NULL DEFAULT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Ruta` VARCHAR(100) NULL DEFAULT NULL,
  `Observacion` VARCHAR(100) NULL DEFAULT NULL,
  `Imagen` BLOB NULL DEFAULT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pacientes` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Identificacion` VARCHAR(13) NOT NULL,
  `Nombre` VARCHAR(70) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(10) NOT NULL,
  `Etnia` VARCHAR(100) NOT NULL,
  `EstadoCivil` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(70) NULL DEFAULT NULL,
  `Telefono` VARCHAR(25) NULL DEFAULT NULL,
  `Celular` VARCHAR(25) NULL DEFAULT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `ContactoEmergencia` VARCHAR(250) NULL DEFAULT NULL,
  `AntecedentePatalogico` TEXT NULL DEFAULT NULL,
  `Contrasenia` VARCHAR(100) NOT NULL,
  `GrupoSanguineo` VARCHAR(45) NULL,
  `Ocupacion` VARCHAR(200) NULL,
  `IdEmpresa` INT(11) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  `IdProvincia` INT NULL,
  `IdCiudad` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `Fk_CiudadPaciente` ON `pacientes` (`IdCiudad` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `Fk_ProvinciaPaciente` ON `pacientes` (`IdProvincia` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `piezadental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piezadental` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `piezadental` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Numero` INT(2) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `profesionales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profesionales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `profesionales` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Identificacion` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(70) NOT NULL,
  `Especialidad` VARCHAR(200) NOT NULL,
  `Correo` VARCHAR(70) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Telefono` VARCHAR(25) NULL DEFAULT NULL,
  `Celular` VARCHAR(25) NULL DEFAULT NULL,
  `FormacionAcademica` TEXT NULL DEFAULT NULL,
  `IdEmpresa` INT(11) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `recetacitageneral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recetacitageneral` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `recetacitageneral` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdCitaGeneral` INT(11) NOT NULL,
  `Diagnostico` VARCHAR(255) NOT NULL,
  `Medicamento` VARCHAR(255) NOT NULL,
  `Dosis` VARCHAR(255) NOT NULL,
  `deleted_at` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Contrasenia` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` INT(11) NOT NULL,
  `IdRol` INT NULL,
  `Activo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;

SHOW WARNINGS;
CREATE INDEX `Fk_idRol` ON `usuarios` (`IdRol` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
